baseURL = "/" #"https://lidders.gitlab.io/blog"
languageCode = "en-uk"
title = "Jon's Project Pages"
theme = "mainroad"
paginate = "10" # Number of posts per page

disqusShortname = "lidders" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Jon Lidgard"
    bio = "my bio"
    avatar = "img/avatar.png"


[Params]
    subtitle = "" # Subtitle of your site
    description = " My personal blog" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
